#******************************************************************************
#
#      MARTe library
#      $Log: Makefile.linux,v $
#      Revision 1.1  2009/10/14 15:50:18  abarb
#      MDSplus Segment first partial version
#
#
#******************************************************************************

TARGET=linux

include Makefile.inc

LIBRARIES   += -L../BaseLib2/$(TARGET) -lBaseLib2
