#*******************************************************************************
#      $Log: Makefile.linux,v $
#*******************************************************************************/

TARGET=linux

include Makefile.inc


LIBRARIES += -L../../BaseLib2/$(TARGET) -lBaseLib2
LIBRARIES += -L../../MARTe/MARTeSupportLib/$(TARGET) -lMARTeSupLib
LIBRARIES += -L/usr/local/mdsplus/lib -lMdsObjectsCppShr

OPTIM=
