
/*
 * Copyright 2011 EFDA | European Fusion Development Agreement
 *
 * Licensed under the EUPL, Version 1.1 or - as soon they 
   will be approved by the European Commission - subsequent  
   versions of the EUPL (the "Licence"); 
 * You may not use this work except in compliance with the 
   Licence. 
 * You may obtain a copy of the Licence at: 
 *  
 * http://ec.europa.eu/idabc/eupl
 *
 * Unless required by applicable law or agreed to in 
   writing, software distributed under the Licence is 
   distributed on an "AS IS" basis, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
   express or implied. 
 * See the Licence for the specific language governing 
   permissions and limitations under the Licence. 
 *
 * $Id$
 *
**/

#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/delay.h>
#include <rtai_sched.h>
#include <rtai_shm.h>
#include "../../OSFiles/rtai/C++Sup/global_obj_support.h"
#include "../Level0/SystemRTAI.h"
void VCAssertErrorCondition(void);
EXPORT_SYMBOL(VCAssertErrorCondition);
void VCStaticAssertErrorCondition(void);
EXPORT_SYMBOL(VCStaticAssertErrorCondition);
void CStaticAssertErrorCondition(void);
EXPORT_SYMBOL(CStaticAssertErrorCondition);
void VCISRAssertErrorCondition(void);
EXPORT_SYMBOL(VCISRAssertErrorCondition);
void CISRStaticAssertErrorCondition(void);
EXPORT_SYMBOL(CISRStaticAssertErrorCondition);
void VCAssertPlatformErrorCondition(void);
EXPORT_SYMBOL(VCAssertPlatformErrorCondition);
void LSSetUserAssembleErrorMessageFunction(void);
EXPORT_SYMBOL(LSSetUserAssembleErrorMessageFunction);
void LSSetUserAssembleISRErrorMessageFunction(void);
EXPORT_SYMBOL(LSSetUserAssembleISRErrorMessageFunction);
void CStaticAssertPlatformErrorCondition(void);
EXPORT_SYMBOL(CStaticAssertPlatformErrorCondition);
void VCAssertSocketErrorCondition(void);
EXPORT_SYMBOL(VCAssertSocketErrorCondition);
void LSGetUserAssembleErrorMessageFunction(void);
EXPORT_SYMBOL(LSGetUserAssembleErrorMessageFunction);
void EMFErrorName(void);
EXPORT_SYMBOL(EMFErrorName);
void MEMORYMalloc(void);
EXPORT_SYMBOL(MEMORYMalloc);
void MEMORYFree(void);
EXPORT_SYMBOL(MEMORYFree);
void MEMORYRealloc(void);
EXPORT_SYMBOL(MEMORYRealloc);
void MEMORYDisplayAllocationStatistics(void);
EXPORT_SYMBOL(MEMORYDisplayAllocationStatistics);
void MEMORYStrDup(void);
EXPORT_SYMBOL(MEMORYStrDup);
void MEMORYAllocationStatistics(void);
EXPORT_SYMBOL(MEMORYAllocationStatistics);
void MEMORYCheck(void);
EXPORT_SYMBOL(MEMORYCheck);
void TimerConfigTimer(void);
EXPORT_SYMBOL(TimerConfigTimer);
void TimerConfigAndStartTimer(void);
EXPORT_SYMBOL(TimerConfigAndStartTimer);
void TimerGetTimerUsecPeriod(void);
EXPORT_SYMBOL(TimerGetTimerUsecPeriod);
void TimerResetTimer(void);
EXPORT_SYMBOL(TimerResetTimer);
void TimerInit(void);
EXPORT_SYMBOL(TimerInit);
void TimerStartTimer(void);
EXPORT_SYMBOL(TimerStartTimer);
void TimerStopTimer(void);
EXPORT_SYMBOL(TimerStopTimer);
void TimerShowStats(void);
EXPORT_SYMBOL(TimerShowStats);
void TimerCServiceRoutine(void);
EXPORT_SYMBOL(TimerCServiceRoutine);
void ProcessorClockRate(void);
EXPORT_SYMBOL(ProcessorClockRate);
void ProcessorClockCycle(void);
EXPORT_SYMBOL(ProcessorClockCycle);
void ProcessorName(void);
EXPORT_SYMBOL(ProcessorName);
void ProcessorFamily(void);
EXPORT_SYMBOL(ProcessorFamily);
void ProcessorCharacteristic(void);
EXPORT_SYMBOL(ProcessorCharacteristic);
void ProcessorReScanCPU(void);
EXPORT_SYMBOL(ProcessorReScanCPU);
void GetSleepFrequency(void);
EXPORT_SYMBOL(GetSleepFrequency);
void SetSleepGranularity(void);
EXPORT_SYMBOL(SetSleepGranularity);
void GetSleepGranularity(void);
EXPORT_SYMBOL(GetSleepGranularity);
void GetDateSeconds(void);
EXPORT_SYMBOL(GetDateSeconds);
void ResynchronizeClock(void);
EXPORT_SYMBOL(ResynchronizeClock);
void ThreadsSetPriorityLevel(void);
EXPORT_SYMBOL(ThreadsSetPriorityLevel);
void ThreadsBeginThread(void);
EXPORT_SYMBOL(ThreadsBeginThread);
void ThreadsThreadId(void);
EXPORT_SYMBOL(ThreadsThreadId);
void ThreadsKill(void);
EXPORT_SYMBOL(ThreadsKill);
void ThreadsIsAlive(void);
EXPORT_SYMBOL(ThreadsIsAlive);
void ThreadsSetNormalClass(void);
EXPORT_SYMBOL(ThreadsSetNormalClass);
void ThreadsSetRealTimeClass(void);
EXPORT_SYMBOL(ThreadsSetRealTimeClass);
void ThreadsSetIdleClass(void);
EXPORT_SYMBOL(ThreadsSetIdleClass);
void ThreadsSetHighClass(void);
EXPORT_SYMBOL(ThreadsSetHighClass);
void ThreadsSetInitialisationInterfaceConstructor(void);
EXPORT_SYMBOL(ThreadsSetInitialisationInterfaceConstructor);
void ThreadsGetInitialisationInterface(void);
EXPORT_SYMBOL(ThreadsGetInitialisationInterface);
void ThreadProtectedExecute(void);
EXPORT_SYMBOL(ThreadProtectedExecute);
void GetHttpRelayURL(void);
EXPORT_SYMBOL(GetHttpRelayURL);
void SetLoggerServerURL(void);
EXPORT_SYMBOL(SetLoggerServerURL);
void TDB_NewEntry(void);
EXPORT_SYMBOL(TDB_NewEntry);
void TDB_RemoveEntry(void);
EXPORT_SYMBOL(TDB_RemoveEntry);
void TDB_GetTII(void);
EXPORT_SYMBOL(TDB_GetTII);
void TDB_Lock(void);
EXPORT_SYMBOL(TDB_Lock);
void TDB_UnLock(void);
EXPORT_SYMBOL(TDB_UnLock);
void TDB_NumberOfThreads(void);
EXPORT_SYMBOL(TDB_NumberOfThreads);
void TDB_GetThreadID(void);
EXPORT_SYMBOL(TDB_GetThreadID);
void TDB_Find(void);
EXPORT_SYMBOL(TDB_Find);
void TDB_GetInfo(void);
EXPORT_SYMBOL(TDB_GetInfo);
void TDB_GetName(void);
EXPORT_SYMBOL(TDB_GetName);
void HRTSystemMsecTime(void);
EXPORT_SYMBOL(HRTSystemMsecTime);
void HRTClockRate(void);
EXPORT_SYMBOL(HRTClockRate);
void HRTClockCycle(void);
EXPORT_SYMBOL(HRTClockCycle);
void HRTMSecTics(void);
EXPORT_SYMBOL(HRTMSecTics);
void MainHandler(void);
EXPORT_SYMBOL(MainHandler);
void SMInit(void);
EXPORT_SYMBOL(SMInit);
void SMCreate(void);
EXPORT_SYMBOL(SMCreate);
void SMOpenExisting(void);
EXPORT_SYMBOL(SMOpenExisting);
void SMDispose(void);
EXPORT_SYMBOL(SMDispose);
void SMGive(void);
EXPORT_SYMBOL(SMGive);
void SemNameDataBaseErase(void);
EXPORT_SYMBOL(SemNameDataBaseErase);
void SemNameDataBaseList(void);
EXPORT_SYMBOL(SemNameDataBaseList);
void SemNameDataBaseAdd(void);
EXPORT_SYMBOL(SemNameDataBaseAdd);
void SemNameDataBaseUseExisting2(void);
EXPORT_SYMBOL(SemNameDataBaseUseExisting2);
void SemNameDataBaseUseExisting(void);
EXPORT_SYMBOL(SemNameDataBaseUseExisting);
void SemNameDataBaseDelete(void);
EXPORT_SYMBOL(SemNameDataBaseDelete);
void CPrintInt32(void);
EXPORT_SYMBOL(CPrintInt32);
void CPrintDouble(void);
EXPORT_SYMBOL(CPrintDouble);
void CPrintString(void);
EXPORT_SYMBOL(CPrintString);
void VCPrintf(void);
EXPORT_SYMBOL(VCPrintf);
void CGetToken(void);
EXPORT_SYMBOL(CGetToken);
void CSkipTokens(void);
EXPORT_SYMBOL(CSkipTokens);
void CGetCStringToken(void);
EXPORT_SYMBOL(CGetCStringToken);
void CDestructiveGetCStringToken(void);
EXPORT_SYMBOL(CDestructiveGetCStringToken);
void CGetCSToken(void);
EXPORT_SYMBOL(CGetCSToken);
void CRead(void);
EXPORT_SYMBOL(CRead);
void CWrite(void);
EXPORT_SYMBOL(CWrite);
void CPrintf(void);
EXPORT_SYMBOL(CPrintf);
void bl2_vsprintf(void);
EXPORT_SYMBOL(bl2_vsprintf);
void bl2_sprintf(void);
EXPORT_SYMBOL(bl2_sprintf);
void bl2_vsnprintf(void);
EXPORT_SYMBOL(bl2_vsnprintf);
void bl2_snprintf(void);
EXPORT_SYMBOL(bl2_snprintf);
void CGetStringToken(void);
EXPORT_SYMBOL(CGetStringToken);
void SocketInit(void);
EXPORT_SYMBOL(SocketInit);
void GetLocalAddress(void);
EXPORT_SYMBOL(GetLocalAddress);
void GetLocalIpNumber(void);
EXPORT_SYMBOL(GetLocalIpNumber);
void GetLocalAddressAsNumber(void);
EXPORT_SYMBOL(GetLocalAddressAsNumber);
void GetHostName(void);
EXPORT_SYMBOL(GetHostName);
void FileOpen(void);
EXPORT_SYMBOL(FileOpen);
void FileLock(void);
EXPORT_SYMBOL(FileLock);
void FileUnLock(void);
EXPORT_SYMBOL(FileUnLock);
void FileSetMaxNumberOfFiles(void);
EXPORT_SYMBOL(FileSetMaxNumberOfFiles);
void FileEraseFile(void);
EXPORT_SYMBOL(FileEraseFile);
void FileSetFileName(void);
EXPORT_SYMBOL(FileSetFileName);
void FileRead(void);
EXPORT_SYMBOL(FileRead);
void FileWrite(void);
EXPORT_SYMBOL(FileWrite);
void FileSize(void);
EXPORT_SYMBOL(FileSize);
void FileSeek(void);
EXPORT_SYMBOL(FileSeek);
void FilePosition(void);
EXPORT_SYMBOL(FilePosition);
void FileSetSize(void);
EXPORT_SYMBOL(FileSetSize);
void FileRelativeSeek(void);
EXPORT_SYMBOL(FileRelativeSeek);
void FilePositionSeek(void);
EXPORT_SYMBOL(FilePositionSeek);
void Get_private_FileInfo(void);
EXPORT_SYMBOL(Get_private_FileInfo);
void ConsoleWrite(void);
EXPORT_SYMBOL(ConsoleWrite);
void ConsoleRead(void);
EXPORT_SYMBOL(ConsoleRead);
void ConsoleSetTitleBar(void);
EXPORT_SYMBOL(ConsoleSetTitleBar);
void ConsoleSetCursorPosition(void);
EXPORT_SYMBOL(ConsoleSetCursorPosition);
void ConsoleSetSize(void);
EXPORT_SYMBOL(ConsoleSetSize);
void ConsoleGetCursorPosition(void);
EXPORT_SYMBOL(ConsoleGetCursorPosition);
void ConsoleGetSize(void);
EXPORT_SYMBOL(ConsoleGetSize);
void RemoteConsoleInit(void);
EXPORT_SYMBOL(RemoteConsoleInit);
void RemoteConsoleFinish(void);
EXPORT_SYMBOL(RemoteConsoleFinish);
void RemoteConsoleWrite(void);
EXPORT_SYMBOL(RemoteConsoleWrite);
void RemoteConsoleRead(void);
EXPORT_SYMBOL(RemoteConsoleRead);
void RCConsoleThread(void);
EXPORT_SYMBOL(RCConsoleThread);
void RCRemoteThread(void);
EXPORT_SYMBOL(RCRemoteThread);
void RemoteConsoleClient(void);
EXPORT_SYMBOL(RemoteConsoleClient);
void ConsoleSetColour(void);
EXPORT_SYMBOL(ConsoleSetColour);
void ConsoleClear(void);
EXPORT_SYMBOL(ConsoleClear);
void ConsoleOpen(void);
EXPORT_SYMBOL(ConsoleOpen);
void ConsoleClose(void);
EXPORT_SYMBOL(ConsoleClose);
void Get_private_ConsoleInfo(void);
EXPORT_SYMBOL(Get_private_ConsoleInfo);
void Get_private_RemoteConsoleInfo(void);
EXPORT_SYMBOL(Get_private_RemoteConsoleInfo);
void ConsoleShow(void);
EXPORT_SYMBOL(ConsoleShow);
void SANameToStreamModes(void);
EXPORT_SYMBOL(SANameToStreamModes);
void ConsoleSetWindowSize(void);
EXPORT_SYMBOL(ConsoleSetWindowSize);
void ConsoleGetWindowSize(void);
EXPORT_SYMBOL(ConsoleGetWindowSize);
void SAColorsToRGB(void);
EXPORT_SYMBOL(SAColorsToRGB);
void ConsolePlotChar(void);
EXPORT_SYMBOL(ConsolePlotChar);
void ATMWrite(void);
EXPORT_SYMBOL(ATMWrite);
void ATMRead(void);
EXPORT_SYMBOL(ATMRead);
void ATMOpen(void);
EXPORT_SYMBOL(ATMOpen);
void ATMSetVCI(void);
EXPORT_SYMBOL(ATMSetVCI);
void ProcessorTypeSetDefaultCPUs(void);
EXPORT_SYMBOL(ProcessorTypeSetDefaultCPUs);
void ProcessorTypeGetDefaultCPUs(void);
EXPORT_SYMBOL(ProcessorTypeGetDefaultCPUs);
void ObjectRegistryDataBaseAdd(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseAdd);
void DisplayRegisteredClasses(void);
EXPORT_SYMBOL(DisplayRegisteredClasses);
void ObjectRegistryDataBaseFind(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseFind);
void ObjectRegistryDataBaseFindByCode(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseFindByCode);
void ObjectRegistryDataBaseFindByExtension(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseFindByExtension);
void ObjectRegistryDataBaseList(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseList);
void ObjectRegistryDataBaseDelete(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseDelete);
void ObjectRegistryDataBaseFindStructure(void);
EXPORT_SYMBOL(ObjectRegistryDataBaseFindStructure);
void ORIInit(void);
EXPORT_SYMBOL(ORIInit);
void ORISetup(void);
EXPORT_SYMBOL(ORISetup);
void ORIFinish(void);
EXPORT_SYMBOL(ORIFinish);
void ORISetupStructure(void);
EXPORT_SYMBOL(ORISetupStructure);
void NameToClassId(void);
EXPORT_SYMBOL(NameToClassId);
void OBJObjectSave(void);
EXPORT_SYMBOL(OBJObjectSave);
void OBJObjectLoadCreate(void);
EXPORT_SYMBOL(OBJObjectLoadCreate);
void OBJObjectCreateByName(void);
EXPORT_SYMBOL(OBJObjectCreateByName);
void OBJObjectCreateById(void);
EXPORT_SYMBOL(OBJObjectCreateById);
void OBJObjectReadFlags(void);
EXPORT_SYMBOL(OBJObjectReadFlags);
void OBJEnableAllocationMonitoring(void);
EXPORT_SYMBOL(OBJEnableAllocationMonitoring);
void OBJDeleteFun(void);
EXPORT_SYMBOL(OBJDeleteFun);
void OBJNewFun(void);
EXPORT_SYMBOL(OBJNewFun);
void OBJSetGlobalOnErrorBehaviour(void);
EXPORT_SYMBOL(OBJSetGlobalOnErrorBehaviour);
void OBJSetThreadOnErrorBehaviour(void);
EXPORT_SYMBOL(OBJSetThreadOnErrorBehaviour);
void OBJSetClassOnErrorBehaviour(void);
EXPORT_SYMBOL(OBJSetClassOnErrorBehaviour);
void OBJSetObjectOnErrorBehaviour(void);
EXPORT_SYMBOL(OBJSetObjectOnErrorBehaviour);
void OBJGetGlobalInstructions(void);
EXPORT_SYMBOL(OBJGetGlobalInstructions);
void OBJGetGlobalErrorAction(void);
EXPORT_SYMBOL(OBJGetGlobalErrorAction);
void Get_private_ObjectInfo(void);
EXPORT_SYMBOL(Get_private_ObjectInfo);
void Get_private_GCNamedObjectInfo(void);
EXPORT_SYMBOL(Get_private_GCNamedObjectInfo);
void GCRConstructor(void);
EXPORT_SYMBOL(GCRConstructor);
void GCRCFind(void);
EXPORT_SYMBOL(GCRCFind);
void GCRCObjectLoadSetup(void);
EXPORT_SYMBOL(GCRCObjectLoadSetup);
void GCRCObjectSaveSetup(void);
EXPORT_SYMBOL(GCRCObjectSaveSetup);
void Get_private_GCReferenceContainerInfo(void);
EXPORT_SYMBOL(Get_private_GCReferenceContainerInfo);
void _GetGlobalObjectDataBase(void);
EXPORT_SYMBOL(_GetGlobalObjectDataBase);
void GCRCInsert(void);
EXPORT_SYMBOL(GCRCInsert);
void GCRCIterate(void);
EXPORT_SYMBOL(GCRCIterate);
void GCRObjectLoadSetup(void);
EXPORT_SYMBOL(GCRObjectLoadSetup);
void GCRObjectSaveSetup(void);
EXPORT_SYMBOL(GCRObjectSaveSetup);
void GlobalObjectDataBaseEnableDebugging(void);
EXPORT_SYMBOL(GlobalObjectDataBaseEnableDebugging);
void GCNOObjectLoadSetup(void);
EXPORT_SYMBOL(GCNOObjectLoadSetup);
void GCRCILReference(void);
EXPORT_SYMBOL(GCRCILReference);
void GCNOObjectSaveSetup(void);
EXPORT_SYMBOL(GCNOObjectSaveSetup);
void BTConvertToString(void);
EXPORT_SYMBOL(BTConvertToString);
void BTConvertFromString(void);
EXPORT_SYMBOL(BTConvertFromString);
void BTConvert(void);
EXPORT_SYMBOL(BTConvert);
void StringToInt64(void);
EXPORT_SYMBOL(StringToInt64);
void Int64ToString(void);
EXPORT_SYMBOL(Int64ToString);
void IntToInt(void);
EXPORT_SYMBOL(IntToInt);
void IntToInt64(void);
EXPORT_SYMBOL(IntToInt64);
void IntToInt32(void);
EXPORT_SYMBOL(IntToInt32);
void Int64ToInt(void);
EXPORT_SYMBOL(Int64ToInt);
void Int32ToInt(void);
EXPORT_SYMBOL(Int32ToInt);
void GCDecrement(void);
EXPORT_SYMBOL(GCDecrement);
void GCIncrement(void);
EXPORT_SYMBOL(GCIncrement);
void CStreamBufferingReadFN(void);
EXPORT_SYMBOL(CStreamBufferingReadFN);
void CStreamBufferingWriteFN(void);
EXPORT_SYMBOL(CStreamBufferingWriteFN);
void CStreamBufferingSeekFN(void);
EXPORT_SYMBOL(CStreamBufferingSeekFN);
void Get_private_StreamableInfo(void);
EXPORT_SYMBOL(Get_private_StreamableInfo);
void StreamCompleteRead(void);
EXPORT_SYMBOL(StreamCompleteRead);
void StreamCompleteWrite(void);
EXPORT_SYMBOL(StreamCompleteWrite);
void FSAlloc(void);
EXPORT_SYMBOL(FSAlloc);
void FSRead(void);
EXPORT_SYMBOL(FSRead);
void FSWrite(void);
EXPORT_SYMBOL(FSWrite);
void Get_private_GCNStringInfo(void);
EXPORT_SYMBOL(Get_private_GCNStringInfo);
void Get_private_ATMSocketInfo(void);
EXPORT_SYMBOL(Get_private_ATMSocketInfo);
void Get_private_UDPSocketInfo(void);
EXPORT_SYMBOL(Get_private_UDPSocketInfo);
void Get_private_TCPSocketInfo(void);
EXPORT_SYMBOL(Get_private_TCPSocketInfo);
void ConsoleSSWrite(void);
EXPORT_SYMBOL(ConsoleSSWrite);
void ConsoleSSRead(void);
EXPORT_SYMBOL(ConsoleSSRead);
void SerialCommitSettings(void);
EXPORT_SYMBOL(SerialCommitSettings);
void SerialToggleControlBits(void);
EXPORT_SYMBOL(SerialToggleControlBits);
void SerialQueryCommStatus(void);
EXPORT_SYMBOL(SerialQueryCommStatus);
void SerialWrite(void);
EXPORT_SYMBOL(SerialWrite);
void SerialRead(void);
EXPORT_SYMBOL(SerialRead);
void SerialOpen(void);
EXPORT_SYMBOL(SerialOpen);
void SerialClose(void);
EXPORT_SYMBOL(SerialClose);
void TestSerial(void);
EXPORT_SYMBOL(TestSerial);
void SerialObjectLoadSetup(void);
EXPORT_SYMBOL(SerialObjectLoadSetup);
void Get_private_SerialInfo(void);
EXPORT_SYMBOL(Get_private_SerialInfo);
void Get_private_BufferedStreamInfo(void);
EXPORT_SYMBOL(Get_private_BufferedStreamInfo);
void Get_private_CDBInfo(void);
EXPORT_SYMBOL(Get_private_CDBInfo);
void CDBC_SortNumFilterFn(void);
EXPORT_SYMBOL(CDBC_SortNumFilterFn);
void CDBC_SortFilterFn(void);
EXPORT_SYMBOL(CDBC_SortFilterFn);
void Get_private_CDBNodeInfo(void);
EXPORT_SYMBOL(Get_private_CDBNodeInfo);
void Get_private_CDBGroupNodeInfo(void);
EXPORT_SYMBOL(Get_private_CDBGroupNodeInfo);
void Get_private_CDBStringDataNodeInfo(void);
EXPORT_SYMBOL(Get_private_CDBStringDataNodeInfo);
void Get_private_CDBLinkNodeInfo(void);
EXPORT_SYMBOL(Get_private_CDBLinkNodeInfo);
void TestCDB(void);
EXPORT_SYMBOL(TestCDB);
void TestCDB2(void);
EXPORT_SYMBOL(TestCDB2);
void TestCDB3(void);
EXPORT_SYMBOL(TestCDB3);
void TestCDB4(void);
EXPORT_SYMBOL(TestCDB4);
void TestCDB5(void);
EXPORT_SYMBOL(TestCDB5);
void TestCDB6(void);
EXPORT_SYMBOL(TestCDB6);
void TestCDB7(void);
EXPORT_SYMBOL(TestCDB7);
void LATokenizeInput(void);
EXPORT_SYMBOL(LATokenizeInput);
void ParserParse(void);
EXPORT_SYMBOL(ParserParse);
void Get_private_ParserInfo(void);
EXPORT_SYMBOL(Get_private_ParserInfo);
void FindCDBTYPEFromCDBDataType(void);
EXPORT_SYMBOL(FindCDBTYPEFromCDBDataType);
void CDBCICreate(void);
EXPORT_SYMBOL(CDBCICreate);
void CDBCIDestroy(void);
EXPORT_SYMBOL(CDBCIDestroy);
void CDBCIClean(void);
EXPORT_SYMBOL(CDBCIClean);
void CDBCILoad(void);
EXPORT_SYMBOL(CDBCILoad);
void CDBCISave(void);
EXPORT_SYMBOL(CDBCISave);
void CDBCIMove(void);
EXPORT_SYMBOL(CDBCIMove);
void CDBCIReadArray(void);
EXPORT_SYMBOL(CDBCIReadArray);
void CDBCIWriteArray(void);
EXPORT_SYMBOL(CDBCIWriteArray);
void CDBCIFree(void);
EXPORT_SYMBOL(CDBCIFree);
void TestCDB8(void);
EXPORT_SYMBOL(TestCDB8);
void TestCDB9(void);
EXPORT_SYMBOL(TestCDB9);
void TestBTInt2Int(void);
EXPORT_SYMBOL(TestBTInt2Int);
void TestBTAny2String(void);
EXPORT_SYMBOL(TestBTAny2String);
void EAFileOpen(void);
EXPORT_SYMBOL(EAFileOpen);
void EAFileAddStream(void);
EXPORT_SYMBOL(EAFileAddStream);
void EAFileClose(void);
EXPORT_SYMBOL(EAFileClose);
void Get_private_EAFileInfo(void);
EXPORT_SYMBOL(Get_private_EAFileInfo);
void ObjectRegistryEvaluateAddress(void);
EXPORT_SYMBOL(ObjectRegistryEvaluateAddress);
void Get_private_StreamConfigurationDataBaseInfo(void);
EXPORT_SYMBOL(Get_private_StreamConfigurationDataBaseInfo);
void Get_float__ORI__(void);
EXPORT_SYMBOL(Get_float__ORI__);
void Get_double__ORI__(void);
EXPORT_SYMBOL(Get_double__ORI__);
void Get_int__ORI__(void);
EXPORT_SYMBOL(Get_int__ORI__);
void Get_long__ORI__(void);
EXPORT_SYMBOL(Get_long__ORI__);
void Get_long_int__ORI__(void);
EXPORT_SYMBOL(Get_long_int__ORI__);
void Get_unsigned_int__ORI__(void);
EXPORT_SYMBOL(Get_unsigned_int__ORI__);
void Get_unsigned_long__ORI__(void);
EXPORT_SYMBOL(Get_unsigned_long__ORI__);
void Get_unsigned_long_int__ORI__(void);
EXPORT_SYMBOL(Get_unsigned_long_int__ORI__);
void Get_short__ORI__(void);
EXPORT_SYMBOL(Get_short__ORI__);
void Get_short_int__ORI__(void);
EXPORT_SYMBOL(Get_short_int__ORI__);
void Get_unsigned_short__ORI__(void);
EXPORT_SYMBOL(Get_unsigned_short__ORI__);
void Get_unsigned_short_int__ORI__(void);
EXPORT_SYMBOL(Get_unsigned_short_int__ORI__);
void Get_char__ORI__(void);
EXPORT_SYMBOL(Get_char__ORI__);
void Get_unsigned_char__ORI__(void);
EXPORT_SYMBOL(Get_unsigned_char__ORI__);
void Get_uint64__ORI__(void);
EXPORT_SYMBOL(Get_uint64__ORI__);
void Get_uint32__ORI__(void);
EXPORT_SYMBOL(Get_uint32__ORI__);
void Get_uint16__ORI__(void);
EXPORT_SYMBOL(Get_uint16__ORI__);
void Get_uint8__ORI__(void);
EXPORT_SYMBOL(Get_uint8__ORI__);
void Get_int64__ORI__(void);
EXPORT_SYMBOL(Get_int64__ORI__);
void Get_int32__ORI__(void);
EXPORT_SYMBOL(Get_int32__ORI__);
void Get_int16__ORI__(void);
EXPORT_SYMBOL(Get_int16__ORI__);
void Get_int8__ORI__(void);
EXPORT_SYMBOL(Get_int8__ORI__);
void md5(void);
EXPORT_SYMBOL(md5);
void B64Encode(void);
EXPORT_SYMBOL(B64Encode);
void B64Decode(void);
EXPORT_SYMBOL(B64Decode);
void MCCService(void);
EXPORT_SYMBOL(MCCService);
void MCCListener(void);
EXPORT_SYMBOL(MCCListener);
void MCCListenerThread(void);
EXPORT_SYMBOL(MCCListenerThread);
void MCCStart(void);
EXPORT_SYMBOL(MCCStart);
void MCCStop(void);
EXPORT_SYMBOL(MCCStop);
void MCCInit(void);
EXPORT_SYMBOL(MCCInit);
void RTMPrint_I(void);
EXPORT_SYMBOL(RTMPrint_I);
void RTMPrint_F(void);
EXPORT_SYMBOL(RTMPrint_F);
void RTMPrint_D(void);
EXPORT_SYMBOL(RTMPrint_D);
void RTMAllocate_I(void);
EXPORT_SYMBOL(RTMAllocate_I);
void RTMAllocate_F(void);
EXPORT_SYMBOL(RTMAllocate_F);
void RTMAllocate_D(void);
EXPORT_SYMBOL(RTMAllocate_D);
void REFMAllocate_I(void);
EXPORT_SYMBOL(REFMAllocate_I);
void REFMAllocate_F(void);
EXPORT_SYMBOL(REFMAllocate_F);
void REFMAllocate_D(void);
EXPORT_SYMBOL(REFMAllocate_D);
void REFMDeAllocate_I(void);
EXPORT_SYMBOL(REFMDeAllocate_I);
void REFMDeAllocate_F(void);
EXPORT_SYMBOL(REFMDeAllocate_F);
void REFMDeAllocate_D(void);
EXPORT_SYMBOL(REFMDeAllocate_D);
void MAReAllocate_I(void);
EXPORT_SYMBOL(MAReAllocate_I);
void MAReAllocate_F(void);
EXPORT_SYMBOL(MAReAllocate_F);
void MAReAllocate_D(void);
EXPORT_SYMBOL(MAReAllocate_D);
void RTM__vecCopy_F(void);
EXPORT_SYMBOL(RTM__vecCopy_F);
void RTM__vecSum_F(void);
EXPORT_SYMBOL(RTM__vecSum_F);
void RTM__vecDiff_F(void);
EXPORT_SYMBOL(RTM__vecDiff_F);
void RTM__vecComb_F(void);
EXPORT_SYMBOL(RTM__vecComb_F);
void RTM__vecScale_F(void);
EXPORT_SYMBOL(RTM__vecScale_F);
void RTM__vecCopy_FI(void);
EXPORT_SYMBOL(RTM__vecCopy_FI);
void RTM__vecCopy_FD(void);
EXPORT_SYMBOL(RTM__vecCopy_FD);
void RTM__vecIsNull_F(void);
EXPORT_SYMBOL(RTM__vecIsNull_F);
void RTM__vecCopy_D(void);
EXPORT_SYMBOL(RTM__vecCopy_D);
void RTM__vecSum_D(void);
EXPORT_SYMBOL(RTM__vecSum_D);
void RTM__vecDiff_D(void);
EXPORT_SYMBOL(RTM__vecDiff_D);
void RTM__vecComb_D(void);
EXPORT_SYMBOL(RTM__vecComb_D);
void RTM__vecScale_D(void);
EXPORT_SYMBOL(RTM__vecScale_D);
void RTM__vecCopy_DF(void);
EXPORT_SYMBOL(RTM__vecCopy_DF);
void RTM__vecCopy_DI(void);
EXPORT_SYMBOL(RTM__vecCopy_DI);
void RTM__vecIsNull_D(void);
EXPORT_SYMBOL(RTM__vecIsNull_D);
void RTM__vecCopy_I(void);
EXPORT_SYMBOL(RTM__vecCopy_I);
void RTM__vecSum_I(void);
EXPORT_SYMBOL(RTM__vecSum_I);
void RTM__vecDiff_I(void);
EXPORT_SYMBOL(RTM__vecDiff_I);
void RTM__vecComb_I(void);
EXPORT_SYMBOL(RTM__vecComb_I);
void RTM__vecScale_I(void);
EXPORT_SYMBOL(RTM__vecScale_I);
void RTM__vecCopy_IF(void);
EXPORT_SYMBOL(RTM__vecCopy_IF);
void RTM__vecCopy_ID(void);
EXPORT_SYMBOL(RTM__vecCopy_ID);
void RTM__vecIsNull_I(void);
EXPORT_SYMBOL(RTM__vecIsNull_I);
void RTMProduct_UIII(void);
EXPORT_SYMBOL(RTMProduct_UIII);
void RTMProduct_UFFF(void);
EXPORT_SYMBOL(RTMProduct_UFFF);
void RTMProduct_UDDD(void);
EXPORT_SYMBOL(RTMProduct_UDDD);
void RTMVProduct_UIII(void);
EXPORT_SYMBOL(RTMVProduct_UIII);
void RTMVProduct_UFFF(void);
EXPORT_SYMBOL(RTMVProduct_UFFF);
void RTMVProduct_UDDD(void);
EXPORT_SYMBOL(RTMVProduct_UDDD);
void RTMVProductAcc_UIII(void);
EXPORT_SYMBOL(RTMVProductAcc_UIII);
void RTMVProductAcc_UFFF(void);
EXPORT_SYMBOL(RTMVProductAcc_UFFF);
void RTMVProductAcc_UDDD(void);
EXPORT_SYMBOL(RTMVProductAcc_UDDD);
void RTMDotProduct_UII(void);
EXPORT_SYMBOL(RTMDotProduct_UII);
void RTMDotProduct_UFF(void);
EXPORT_SYMBOL(RTMDotProduct_UFF);
void RTMDotProduct_UDD(void);
EXPORT_SYMBOL(RTMDotProduct_UDD);
void RTMTranspose_UII(void);
EXPORT_SYMBOL(RTMTranspose_UII);
void RTMTranspose_UFF(void);
EXPORT_SYMBOL(RTMTranspose_UFF);
void RTMTranspose_UDD(void);
EXPORT_SYMBOL(RTMTranspose_UDD);
void RTMInvert_UFF(void);
EXPORT_SYMBOL(RTMInvert_UFF);
void RTMInvert_UDF(void);
EXPORT_SYMBOL(RTMInvert_UDF);
void RTMInvert_UDD(void);
EXPORT_SYMBOL(RTMInvert_UDD);
void RTMLU_FFFF(void);
EXPORT_SYMBOL(RTMLU_FFFF);
void RTMLU_DDDD(void);
EXPORT_SYMBOL(RTMLU_DDDD);
void RTMSVD_FFFF(void);
EXPORT_SYMBOL(RTMSVD_FFFF);
void RTMSVD_DDDD(void);
EXPORT_SYMBOL(RTMSVD_DDDD);
void RTMZerofy_I(void);
EXPORT_SYMBOL(RTMZerofy_I);
void RTMZerofy_F(void);
EXPORT_SYMBOL(RTMZerofy_F);
void RTMZerofy_D(void);
EXPORT_SYMBOL(RTMZerofy_D);
void RTMOnefy_I(void);
EXPORT_SYMBOL(RTMOnefy_I);
void RTMOnefy_F(void);
EXPORT_SYMBOL(RTMOnefy_F);
void RTMOnefy_D(void);
EXPORT_SYMBOL(RTMOnefy_D);
void RTMEyefy_I(void);
EXPORT_SYMBOL(RTMEyefy_I);
void RTMEyefy_F(void);
EXPORT_SYMBOL(RTMEyefy_F);
void RTMEyefy_D(void);
EXPORT_SYMBOL(RTMEyefy_D);
void RTMIsNull_I(void);
EXPORT_SYMBOL(RTMIsNull_I);
void RTMIsNull_F(void);
EXPORT_SYMBOL(RTMIsNull_F);
void RTMIsNull_D(void);
EXPORT_SYMBOL(RTMIsNull_D);
void RTMScale_II(void);
EXPORT_SYMBOL(RTMScale_II);
void RTMScale_FF(void);
EXPORT_SYMBOL(RTMScale_FF);
void RTMScale_DD(void);
EXPORT_SYMBOL(RTMScale_DD);
void RTMMax_I(void);
EXPORT_SYMBOL(RTMMax_I);
void RTMMax_F(void);
EXPORT_SYMBOL(RTMMax_F);
void RTMMax_D(void);
EXPORT_SYMBOL(RTMMax_D);
void RTMMin_I(void);
EXPORT_SYMBOL(RTMMin_I);
void RTMMin_F(void);
EXPORT_SYMBOL(RTMMin_F);
void RTMMin_D(void);
EXPORT_SYMBOL(RTMMin_D);
void RTMCombine_UIIII(void);
EXPORT_SYMBOL(RTMCombine_UIIII);
void RTMCombine_UFFFF(void);
EXPORT_SYMBOL(RTMCombine_UFFFF);
void RTMCombine_UDDDD(void);
EXPORT_SYMBOL(RTMCombine_UDDDD);
void RTMMaxAbsRowSumNorm_I(void);
EXPORT_SYMBOL(RTMMaxAbsRowSumNorm_I);
void RTMMaxAbsRowSumNorm_F(void);
EXPORT_SYMBOL(RTMMaxAbsRowSumNorm_F);
void RTMMaxAbsRowSumNorm_D(void);
EXPORT_SYMBOL(RTMMaxAbsRowSumNorm_D);
void RTMMaxAbsColSumNorm_I(void);
EXPORT_SYMBOL(RTMMaxAbsColSumNorm_I);
void RTMMaxAbsColSumNorm_F(void);
EXPORT_SYMBOL(RTMMaxAbsColSumNorm_F);
void RTMMaxAbsColSumNorm_D(void);
EXPORT_SYMBOL(RTMMaxAbsColSumNorm_D);
void FilterInit(void);
EXPORT_SYMBOL(FilterInit);
void FilterResize(void);
EXPORT_SYMBOL(FilterResize);
void Get_private_FilterInfo(void);
EXPORT_SYMBOL(Get_private_FilterInfo);
void HSUserServiceThreadEx(void);
EXPORT_SYMBOL(HSUserServiceThreadEx);
void HSUserListenerInitialize(void);
EXPORT_SYMBOL(HSUserListenerInitialize);
void HSUserListenerTerminate(void);
EXPORT_SYMBOL(HSUserListenerTerminate);
void HSUserListenerThread(void);
EXPORT_SYMBOL(HSUserListenerThread);
void HSObjectLoadSetup(void);
EXPORT_SYMBOL(HSObjectLoadSetup);
void HSWWrite(void);
EXPORT_SYMBOL(HSWWrite);
void HSWriteHeader(void);
EXPORT_SYMBOL(HSWriteHeader);
void HSWFlush(void);
EXPORT_SYMBOL(HSWFlush);
void Get_private_HttpBasicServiceInfo(void);
EXPORT_SYMBOL(Get_private_HttpBasicServiceInfo);
void Get_private_HttpServiceInfo(void);
EXPORT_SYMBOL(Get_private_HttpServiceInfo);
void Get_private_HttpGroupResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpGroupResourceInfo);
void Get_private_HttpDirectoryResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpDirectoryResourceInfo);
void Get_private_HttpClassListResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpClassListResourceInfo);
void Get_private_HttpClientInfo(void);
EXPORT_SYMBOL(Get_private_HttpClientInfo);
void Get_private_HttpFramedResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpFramedResourceInfo);
void Get_private_HttpErrorLogResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpErrorLogResourceInfo);
void Get_private_HttpServiceRelayResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpServiceRelayResourceInfo);
void Get_private_HttpThreadListResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpThreadListResourceInfo);
void URLLoad(void);
EXPORT_SYMBOL(URLLoad);
void HttpClientGet(void);
EXPORT_SYMBOL(HttpClientGet);
void OBMSetup(void);
EXPORT_SYMBOL(OBMSetup);
void OBMBrowse(void);
EXPORT_SYMBOL(OBMBrowse);
void MenuSystemTextMenu(void);
EXPORT_SYMBOL(MenuSystemTextMenu);
void DDBIAMObjectSaveSetup(void);
EXPORT_SYMBOL(DDBIAMObjectSaveSetup);
void DDBIAddSignal(void);
EXPORT_SYMBOL(DDBIAddSignal);
void DDBCreateLink(void);
EXPORT_SYMBOL(DDBCreateLink);
void DDBAddInterface(void);
EXPORT_SYMBOL(DDBAddInterface);
void DDBCreateLinkToGAM(void);
EXPORT_SYMBOL(DDBCreateLinkToGAM);
void DDBAddGAMInterface(void);
EXPORT_SYMBOL(DDBAddGAMInterface);
void DDBCheckAndAllocate(void);
EXPORT_SYMBOL(DDBCheckAndAllocate);
void DDBPrint(void);
EXPORT_SYMBOL(DDBPrint);
void DDBIObjectLoadSetup(void);
EXPORT_SYMBOL(DDBIObjectLoadSetup);
void DDBIObjectSaveSetup(void);
EXPORT_SYMBOL(DDBIObjectSaveSetup);
void Get_private_DDBInterfaceInfo(void);
EXPORT_SYMBOL(Get_private_DDBInterfaceInfo);
void DDBIDObjectLoadSetup(void);
EXPORT_SYMBOL(DDBIDObjectLoadSetup);
void DDBIFinalise(void);
EXPORT_SYMBOL(DDBIFinalise);
void DDBIFind(void);
EXPORT_SYMBOL(DDBIFind);
void Get_private_DDBInterfaceDescriptorInfo(void);
EXPORT_SYMBOL(Get_private_DDBInterfaceDescriptorInfo);
void DDBSD(void);
EXPORT_SYMBOL(DDBSD);
void DDBSD2(void);
EXPORT_SYMBOL(DDBSD2);
void DDBISignalsList(void);
EXPORT_SYMBOL(DDBISignalsList);
void DDBIBufferWordSize(void);
EXPORT_SYMBOL(DDBIBufferWordSize);
void DDBObjectLoadSetup(void);
EXPORT_SYMBOL(DDBObjectLoadSetup);
void DDBObjectSaveSetup(void);
EXPORT_SYMBOL(DDBObjectSaveSetup);
void DDBISignalRename(void);
EXPORT_SYMBOL(DDBISignalRename);
void GAMAddInputInterface(void);
EXPORT_SYMBOL(GAMAddInputInterface);
void GAMAddOutputInterface(void);
EXPORT_SYMBOL(GAMAddOutputInterface);
void GAMAddIOInterface(void);
EXPORT_SYMBOL(GAMAddIOInterface);
void GAMFinaliseInterfaces(void);
EXPORT_SYMBOL(GAMFinaliseInterfaces);
void GAMRemapInterfaces(void);
EXPORT_SYMBOL(GAMRemapInterfaces);
void GAMGetPersistentCDB(void);
EXPORT_SYMBOL(GAMGetPersistentCDB);
void GAMUpdatePersistentCDB(void);
EXPORT_SYMBOL(GAMUpdatePersistentCDB);
void SMObjectLoadSetup(void);
EXPORT_SYMBOL(SMObjectLoadSetup);
void SMObjectSaveSetup(void);
EXPORT_SYMBOL(SMObjectSaveSetup);
void SMProcessMessage(void);
EXPORT_SYMBOL(SMProcessMessage);
void SMSObjectLoadSetup(void);
EXPORT_SYMBOL(SMSObjectLoadSetup);
void SMSObjectSaveSetup(void);
EXPORT_SYMBOL(SMSObjectSaveSetup);
void SMEObjectLoadSetup(void);
EXPORT_SYMBOL(SMEObjectLoadSetup);
void SMEObjectSaveSetup(void);
EXPORT_SYMBOL(SMEObjectSaveSetup);
void SMProcessHttpMessage(void);
EXPORT_SYMBOL(SMProcessHttpMessage);
void MessageHandlerThreadFN(void);
EXPORT_SYMBOL(MessageHandlerThreadFN);
void MSGObjectLoadSetup(void);
EXPORT_SYMBOL(MSGObjectLoadSetup);
void MSGObjectSaveSetup(void);
EXPORT_SYMBOL(MSGObjectSaveSetup);
void MSGGetUniqueId(void);
EXPORT_SYMBOL(MSGGetUniqueId);
void MSGEObjectLoadSetup(void);
EXPORT_SYMBOL(MSGEObjectLoadSetup);
void MSGEObjectSaveSetup(void);
EXPORT_SYMBOL(MSGEObjectSaveSetup);
void MSGEPrepareMessageEnvelope(void);
EXPORT_SYMBOL(MSGEPrepareMessageEnvelope);
void MSGEPrepareReply(void);
EXPORT_SYMBOL(MSGEPrepareReply);
void MDRObjectLoadSetup(void);
EXPORT_SYMBOL(MDRObjectLoadSetup);
void MDRObjectSaveSetup(void);
EXPORT_SYMBOL(MDRObjectSaveSetup);
void GlobalMessageDispatcher(void);
EXPORT_SYMBOL(GlobalMessageDispatcher);
void MDRPrepareMDR(void);
EXPORT_SYMBOL(MDRPrepareMDR);
void MCProcessHttpMessage(void);
EXPORT_SYMBOL(MCProcessHttpMessage);
void SendMenuMessage(void);
EXPORT_SYMBOL(SendMenuMessage);
void ExecuteMenuAction(void);
EXPORT_SYMBOL(ExecuteMenuAction);
void SSMHIProcessMessage(void);
EXPORT_SYMBOL(SSMHIProcessMessage);
void MHHandleMessage(void);
EXPORT_SYMBOL(MHHandleMessage);
void MHConstructor(void);
EXPORT_SYMBOL(MHConstructor);
void MHSendMessage(void);
EXPORT_SYMBOL(MHSendMessage);
void MHSendMessageAndWait(void);
EXPORT_SYMBOL(MHSendMessageAndWait);
void MBProcessMessage2(void);
EXPORT_SYMBOL(MBProcessMessage2);
void MBObjectLoadSetup(void);
EXPORT_SYMBOL(MBObjectLoadSetup);
void MBObjectSaveSetup(void);
EXPORT_SYMBOL(MBObjectSaveSetup);
void MessageServerThreadFN(void);
EXPORT_SYMBOL(MessageServerThreadFN);
void MSObjectLoadSetup(void);
EXPORT_SYMBOL(MSObjectLoadSetup);
void MSObjectSaveSetup(void);
EXPORT_SYMBOL(MSObjectSaveSetup);
void MHSendMessageRemotely(void);
EXPORT_SYMBOL(MHSendMessageRemotely);
void Get_private_CDBBrowserMenuInfo(void);
EXPORT_SYMBOL(Get_private_CDBBrowserMenuInfo);
void Get_private_MMCDBInfo(void);
EXPORT_SYMBOL(Get_private_MMCDBInfo);
void Get_private_GAMInfo(void);
EXPORT_SYMBOL(Get_private_GAMInfo);
void Get_private_DDBInfo(void);
EXPORT_SYMBOL(Get_private_DDBInfo);
void Get_private_MessageInfo(void);
EXPORT_SYMBOL(Get_private_MessageInfo);
void Get_private_MessageEnvelopeInfo(void);
EXPORT_SYMBOL(Get_private_MessageEnvelopeInfo);
void Get_private_MenuContainerInfo(void);
EXPORT_SYMBOL(Get_private_MenuContainerInfo);
void Get_private_MenuEntryInfo(void);
EXPORT_SYMBOL(Get_private_MenuEntryInfo);
void Get_private_MessageDeliveryRequestInfo(void);
EXPORT_SYMBOL(Get_private_MessageDeliveryRequestInfo);
void Get_private_MessageDispatcherInfo(void);
EXPORT_SYMBOL(Get_private_MessageDispatcherInfo);
void Get_private_StateMachineInfo(void);
EXPORT_SYMBOL(Get_private_StateMachineInfo);
void Get_private_StateMachineStateInfo(void);
EXPORT_SYMBOL(Get_private_StateMachineStateInfo);
void Get_private_StateMachineEventInfo(void);
EXPORT_SYMBOL(Get_private_StateMachineEventInfo);
void Get_private_HttpMessageSendResourceInfo(void);
EXPORT_SYMBOL(Get_private_HttpMessageSendResourceInfo);
void Get_private_HttpDigestRealmInfo(void);
EXPORT_SYMBOL(Get_private_HttpDigestRealmInfo);
void Get_private_HttpLocalSecurityBasicRealmInfo(void);
EXPORT_SYMBOL(Get_private_HttpLocalSecurityBasicRealmInfo);
void Get_private_SignalInfo(void);
EXPORT_SYMBOL(Get_private_SignalInfo);
void Get_private_SendMessageMenuEntryInfo(void);
EXPORT_SYMBOL(Get_private_SendMessageMenuEntryInfo);
void Get_private_ExecuteMenuEntryInfo(void);
EXPORT_SYMBOL(Get_private_ExecuteMenuEntryInfo);
void DDBBrowseMenu(void);
EXPORT_SYMBOL(DDBBrowseMenu);
void DDBDumpMenu(void);
EXPORT_SYMBOL(DDBDumpMenu);
void DIRMenuSystemTextMenu(void);
EXPORT_SYMBOL(DIRMenuSystemTextMenu);
void DIRMProcessHttpMessage(void);
EXPORT_SYMBOL(DIRMProcessHttpMessage);
void Get_private_DirectoryMenuBrowserInfo(void);
EXPORT_SYMBOL(Get_private_DirectoryMenuBrowserInfo);
void ExceptionHandlerInstallTIIC(void);
EXPORT_SYMBOL(ExceptionHandlerInstallTIIC);
void CDB2Setup(void);
EXPORT_SYMBOL(CDB2Setup);
void CDB2Browse(void);
EXPORT_SYMBOL(CDB2Browse);
void CDBHUHtmlObjectSubView(void);
EXPORT_SYMBOL(CDBHUHtmlObjectSubView);
void LoadDimension(void);
EXPORT_SYMBOL(LoadDimension);
void LoadMatrixObject(void);
EXPORT_SYMBOL(LoadMatrixObject);
void LoadVectorObject(void);
EXPORT_SYMBOL(LoadVectorObject);
void LoadSingleObject(void);
EXPORT_SYMBOL(LoadSingleObject);
void LoadRTMatrixObject(void);
EXPORT_SYMBOL(LoadRTMatrixObject);
void B2C_CreateGODBObject(void);
EXPORT_SYMBOL(B2C_CreateGODBObject);
void B2C_CreateAndInitialiseGODBObject(void);
EXPORT_SYMBOL(B2C_CreateAndInitialiseGODBObject);
void B2C_InitialiseGODBObject(void);
EXPORT_SYMBOL(B2C_InitialiseGODBObject);
void B2C_DeleteGODBSubTree(void);
EXPORT_SYMBOL(B2C_DeleteGODBSubTree);
void B2C_ListGODBNodes(void);
EXPORT_SYMBOL(B2C_ListGODBNodes);
void B2C_ShowGODBSubTree(void);
EXPORT_SYMBOL(B2C_ShowGODBSubTree);
void B2C_SendMessageToGODBObject(void);
EXPORT_SYMBOL(B2C_SendMessageToGODBObject);
void SMIGetSignal(void);
EXPORT_SYMBOL(SMIGetSignal);
void SMIProcessMessage(void);
EXPORT_SYMBOL(SMIProcessMessage);
void MCSaveF(void);
EXPORT_SYMBOL(MCSaveF);
void MCSaveD(void);
EXPORT_SYMBOL(MCSaveD);
void MCSaveMF(void);
EXPORT_SYMBOL(MCSaveMF);
void MCSaveMD(void);
EXPORT_SYMBOL(MCSaveMD);
void MCSaveMI(void);
EXPORT_SYMBOL(MCSaveMI);
void MCSaveS(void);
EXPORT_SYMBOL(MCSaveS);
void Get_private_SignalArchiverInfo(void);
EXPORT_SYMBOL(Get_private_SignalArchiverInfo);
void Get_private_HttpGCRCBrowserInfo(void);
EXPORT_SYMBOL(Get_private_HttpGCRCBrowserInfo);
void ESIInit(void);
EXPORT_SYMBOL(ESIInit);
void ESILoad(void);
EXPORT_SYMBOL(ESILoad);
void ESISend(void);
EXPORT_SYMBOL(ESISend);
void ESIFromBuffer(void);
EXPORT_SYMBOL(ESIFromBuffer);
void ESIComposeToText(void);
EXPORT_SYMBOL(ESIComposeToText);
void GetLogStream(void);
EXPORT_SYMBOL(GetLogStream);
void EndLogStream(void);
EXPORT_SYMBOL(EndLogStream);
void LSStartService(void);
EXPORT_SYMBOL(LSStartService);
void LSStopService(void);
EXPORT_SYMBOL(LSStopService);
void LSProcessPendingErrors(void);
EXPORT_SYMBOL(LSProcessPendingErrors);
void WSAMain(void);
EXPORT_SYMBOL(WSAMain);
void LSAssembleErrorMessage(void);
EXPORT_SYMBOL(LSAssembleErrorMessage);

/*
 * Copyright 2011 EFDA | European Fusion Development Agreement
 *
 * Licensed under the EUPL, Version 1.1 or - as soon they 
   will be approved by the European Commission - subsequent  
   versions of the EUPL (the "Licence"); 
 * You may not use this work except in compliance with the 
   Licence. 
 * You may obtain a copy of the Licence at: 
 *  
 * http://ec.europa.eu/idabc/eupl
 *
 * Unless required by applicable law or agreed to in 
   writing, software distributed under the Licence is 
   distributed on an "AS IS" basis, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
   express or implied. 
 * See the Licence for the specific language governing 
   permissions and limitations under the Licence. 
 *
 * $Id$
 *
**/

int init_func(void)
{
//init_all_constructors and delete_all_deconstructors are now called from the
//RTAIConsole
    printk("Init BaseLib2 module...\n");
    
    return 0;
}

void exit_func(void)
{
    
    printk("Exit module BaseLib2\n");
}

module_init(init_func);
module_exit(exit_func);
