#******************************************************************************
#      RTAIConsole
#      $Id: Makefile.linux,v 1.1 2008/10/27 12:06:37 rvitelli Exp $
#******************************************************************************

TARGET=linux

include Makefile.inc

OPTIM = -finline-functions
